import Head from 'next/head'
import Image from 'next/image';
import 'antd/dist/antd.css';
import detectEthereumProvider from '@metamask/detect-provider';
import styles from '../styles/Home.module.css'
import { message } from 'antd';

export default function Home() {
  console.log('Home page called');

  // it opens metamask mobile app like in opensea
  const openLikeOpenSea = () => {
    const { ethereum } = window;
    if (ethereum && ethereum.isMetaMask) {
      message.info('Metamask is present');
      console.log('Ethereum successfully detected!');
      // Access the decentralized web!
    } else {
      message.error('Metamask not present, check if we can launch metamask or not');
      // showCustomNotification(
      //   'warning',
      //   'Metamask needed now',
      //   'Okokok'
      // );
      console.log('Please install MetaMask!');
    }
    // we need use deeplink url here to open metamask mobile app
    window.open("https://metamask.app.link/dapp/5ea7-42-107-68-31.in.ngrok.io")
  }

  // it uses provider works on desktop does not work on mobile
  const openMetamask = async () => {
    console.log('openMetamask called');
    const provider = await detectEthereumProvider();

    if (provider) {
      // From now on, this should always be true:
      // provider === window.ethereum
      // startApp(provider); // initialize your app
      message.error('Metamask provider found');
      console.log('openMetamask called with provider =', provider);
    } else {
      message.error('Metamask provider not found');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile Metamask App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div style={{ marginTop: 40, margnleft: 40 }}>
       <button onClick={openLikeOpenSea}>Open Metamask</button>
     </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
